-- V1: core domain schema (Day 2, PYMK_ROADMAP.md Week 1).
-- Covers: members, connections, member_events.
-- member_embeddings (pgvector) lands in V2 on Day 5.
-- pymk_features (feature store) lands later, Week 3 Day 15.

-- ============================================================
-- members
-- ============================================================
-- id is NOT auto-generated: member IDs are assigned by the synthetic data
-- generator (Day 4), mirroring an upstream identity service owning the ID
-- space in a real system.
CREATE TABLE members (
    id          BIGINT PRIMARY KEY,
    full_name   VARCHAR(255) NOT NULL,
    headline    VARCHAR(255),
    company     VARCHAR(255),
    school      VARCHAR(255),
    geo_region  VARCHAR(255),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Supports HeuristicCandidateSource (Day 8): same-company/school/geo lookups.
CREATE INDEX idx_members_company ON members (company);
CREATE INDEX idx_members_school ON members (school);
CREATE INDEX idx_members_geo_region ON members (geo_region);

-- ============================================================
-- connections
-- ============================================================
-- Symmetric edge list: an accepted connection between A and B is stored as
-- two rows, (A, B) and (B, A), trading storage for O(1) adjacency lookups
-- in either direction (see PYMK_DESIGN.md 5.2 and GraphWalkCandidateSource,
-- Day 9's recursive CTE).
CREATE TABLE connections (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id            BIGINT NOT NULL REFERENCES members (id),
    connected_member_id  BIGINT NOT NULL REFERENCES members (id),
    connected_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_connections_not_self CHECK (member_id <> connected_member_id),
    CONSTRAINT uq_connections_pair UNIQUE (member_id, connected_member_id)
);

-- Named to match the @Index annotations on the Connection entity.
CREATE INDEX idx_conn_member ON connections (member_id);
CREATE INDEX idx_conn_connected ON connections (connected_member_id);

-- ============================================================
-- member_events
-- ============================================================
-- Raw engagement event log (profile views, search appearances, invite
-- lifecycle). Aggregated into pymk_features by FeatureComputationJob
-- (Day 17); INVITE_ACCEPTED rows become positive training labels (Day 18).
CREATE TABLE member_events (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_member_id   BIGINT NOT NULL REFERENCES members (id),
    target_member_id  BIGINT NOT NULL REFERENCES members (id),
    type              VARCHAR(32) NOT NULL CHECK (
                          type IN (
                              'PROFILE_VIEW',
                              'SEARCH_APPEARANCE',
                              'INVITE_SENT',
                              'INVITE_ACCEPTED',
                              'INVITE_IGNORED'
                          )
                      ),
    occurred_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_event_actor ON member_events (actor_member_id);
CREATE INDEX idx_event_target_type ON member_events (target_member_id, type);
CREATE INDEX idx_event_occurred_at ON member_events (occurred_at);
